/* ═══════════════════════════════════════════════════════════════════════════
   KALKI — Bake FolioChunk embeddings into db/custom.db (Leak L4)
   ---------------------------------------------------------------------------
   Run from repo root:   npx tsx scripts/bake-folio-embeddings.ts

   What it does:
     1. Reads all FolioChunk rows from the baked corpus db/custom.db.
     2. Computes document-frequency over the shared tokenizer (src/lib/rag/embed.ts)
        and builds the term→IDF map (idf = ln((N+1)/(df+1)) + 1, 6-dp rounded).
     3. Generates src/lib/rag/idf-generated.ts (the runtime query-side lookup).
     4. Embeds every chunk with the SAME lookup the runtime will use and
        UPDATEs FolioChunk.embedding in place (JSON float array, 512 dims).
     5. Re-reads the baked vectors from the DB and runs a retrieval sanity
        panel (cosine top-4 per sample query) as the round-trip proof.

   To swap in a neural provider later: keep the same script shape — replace
   embedText with the provider call inside the loop and regenerate the IDF
   module only if the provider still needs it (neural: remove the import of
   idf-generated from retrieval path; the cosine contract stays identical).
   ═══════════════════════════════════════════════════════════════════════════ */

import { createClient } from '@libsql/client';
import { writeFileSync, statSync } from 'fs';
import { join } from 'path';
import {
  embedText,
  makeIdfLookup,
  tokenTerms,
  EMBED_DIM,
  EMBED_MODEL,
} from '../src/lib/rag/embed';

const ROOT = process.cwd();
const DB_PATH = join(ROOT, 'db', 'custom.db');
const IDF_OUT = join(ROOT, 'src', 'lib', 'rag', 'idf-generated.ts');

type Row = { id: string; slug: string; section: string; text: string };

async function main() {
  const client = createClient({ url: `file:${DB_PATH}` });

  // ── 1. Load corpus ──────────────────────────────────────────────────────
  const res = await client.execute(
    'SELECT id, slug, section, text FROM FolioChunk ORDER BY id'
  );
  const rows = res.rows.map((r) => ({
    id: String(r.id),
    slug: String(r.slug),
    section: String(r.section),
    text: String(r.text),
  })) as Row[];
  const N = rows.length;
  if (N === 0) throw new Error('Corpus is empty — aborting.');
  console.log(`[bake] corpus: ${N} chunks from db/custom.db`);

  // ── 2. Document frequency → IDF map ────────────────────────────────────
  const df = new Map<string, number>();
  for (const row of rows) {
    for (const t of new Set(tokenTerms(row.text))) {
      df.set(t, (df.get(t) ?? 0) + 1);
    }
  }
  const idfMap: Record<string, number> = {};
  for (const [term, d] of df) {
    idfMap[term] = Math.round((Math.log((N + 1) / (d + 1)) + 1) * 1e6) / 1e6;
  }
  // The lookup BOTH sides use — bake here, runtime via idf-generated.ts.
  const idf = makeIdfLookup(idfMap, N);
  console.log(`[bake] vocabulary: ${Object.keys(idfMap).length} terms (unigrams + bigrams)`);

  // ── 3. Generate the runtime IDF module ─────────────────────────────────
  const sortedTerms = Object.keys(idfMap).sort();
  const entries = sortedTerms.map((t) => `  ${JSON.stringify(t)}: ${idfMap[t]},`);
  const body = `/* AUTO-GENERATED by scripts/bake-folio-embeddings.ts — DO NOT EDIT BY HAND.
 * Regenerate:  npx tsx scripts/bake-folio-embeddings.ts
 * Model: ${EMBED_MODEL} · dims: ${EMBED_DIM} · corpus: ${N} chunks
 * Terms: ${sortedTerms.length} (unigrams + bigrams, IAST-folded)
 * Regenerate whenever db/custom.db changes; OOV query terms fall back to
 * the default idf ln(N+1)+1 inside makeIdfLookup(). */

export const CORPUS_SIZE = ${N};
export const EMBED_MODEL = '${EMBED_MODEL}';
export const EMBED_DIM = ${EMBED_DIM};

export const IDF: Record<string, number> = {
${entries.join('\n')}
};
`;
  writeFileSync(IDF_OUT, body);
  const kb = Math.round(statSync(IDF_OUT).size / 1024);
  console.log(`[bake] generated src/lib/rag/idf-generated.ts (${kb} KB)`);

  // ── 4. Embed + persist ─────────────────────────────────────────────────
  let done = 0;
  for (const row of rows) {
    const vec = embedText(row.text, idf);
    if (vec.length !== EMBED_DIM) throw new Error(`dim mismatch on ${row.id}`);
    await client.execute({
      sql: 'UPDATE FolioChunk SET embedding = ? WHERE id = ?',
      args: [JSON.stringify(vec), row.id],
    });
    done++;
    if (done % 100 === 0) console.log(`[bake] embedded ${done}/${N}`);
  }
  console.log(`[bake] embedded ${done}/${N} chunks → FolioChunk.embedding`);

  // ── 5. Round-trip sanity panel (reads vectors back FROM the db) ────────
  const baked = await client.execute(
    'SELECT id, slug, section, caution, embedding FROM FolioChunk'
  );
  const bakedRows = baked.rows.map((r) => ({
    slug: String(r.slug),
    section: String(r.section),
    caution: String(r.caution),
    vec: JSON.parse(String(r.embedding)) as number[],
  }));
  const empty = bakedRows.filter((r) => r.vec.length !== EMBED_DIM).length;
  if (empty > 0) throw new Error(`${empty} baked vectors are not ${EMBED_DIM}-dim!`);

  const cosine = (a: number[], b: number[]) => {
    let d = 0, na = 0, nb = 0;
    for (let i = 0; i < EMBED_DIM; i++) { d += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; }
    return d / (Math.sqrt(na) * Math.sqrt(nb) || 1);
  };

  const QUERIES = [
    'constant fear of being judged, I avoid speaking up',
    'procrastination and avoidance of important work',
    'anger outbursts then guilt in close relationships',
    'overthinking at night, cannot sleep',
    'how do I start a daily japa practice',
    'bhairavi sadhana warnings and precautions',
  ];
  console.log('\n[bake] sanity panel — top-4 per query (round-trip from db):');
  for (const q of QUERIES) {
    const qv = embedText(q, idf);
    const top = bakedRows
      .map((r) => ({ ...r, s: cosine(qv, r.vec) }))
      .sort((a, b) => b.s - a.s)
      .slice(0, 4);
    console.log(`\n  Q: "${q}"`);
    for (const t of top) {
      console.log(`    ${t.s.toFixed(4)}  ${t.slug} · ${t.section} · ${t.caution}`);
    }
  }
  console.log('\n[bake] DONE — corpus is retrieval-ready.');
}

main().catch((e) => {
  console.error('[bake] FAILED:', e);
  process.exit(1);
});
